[package]
name = "rat-input"
version = "0.13.1"
edition = "2021"
description = "ratatui text input widgets"
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/rat-input"
readme = "readme.md"
keywords = ["ratatui", "input", "mask"]
categories = ["command-line-interface"]
exclude = [".idea/*", ".gitignore"]

[lints.rust]
absolute_paths_not_starting_with_crate = "warn"
# box_pointers = "warn"
elided_lifetimes_in_paths = "warn"
explicit_outlives_requirements = "warn"
keyword_idents = "warn"
macro_use_extern_crate = "warn"
meta_variable_misuse = "warn"
missing_abi = "warn"
# NOT_ACCURATE: missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "allow"
non_ascii_idents = "warn"
noop_method_call = "warn"
# NO: or_patterns_back_compat = "warn"
pointer_structural_match = "warn"
semicolon_in_expressions_from_macros = "warn"
# NOT_ACCURATE: single_use_lifetimes = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unreachable_pub = "warn"
# unsafe_code: = "warn"
unsafe_op_in_unsafe_fn = "warn"
unstable_features = "warn"
# NO: unused_crate_dependencies = "warn"
# NO: unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
# NO: unused_results = "warn"
variant_size_differences = "warn"

[dependencies]
chrono = { version = "0.4", features = ["unstable-locales"] }
crossterm = "0.27"
ratatui = { version = "0.26", features = ["unstable-widget-ref", "unstable-rendered-line-info"] }
unicode-segmentation = "1.11"
rust_decimal = "1.34"
rust_decimal_macros = "1.34"
pure-rust-locales = "0.8"
memchr = "2.7.2"
format_num_pattern = "0.9"
log = "0.4"
rat-event = "0.12"

[dev-dependencies]
fern = "0.6"
humantime = "2.1"
rand = "0.8.5"
anyhow = "1.0"
